name: CI

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.0'
        cache: 'pip'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install apache-airflow
      run: pip install apache-airflow==2.0.2
    - name: Run linter
      run: flake8
    - name: Run tests
      run: pytest
